### PR TITLE
Bot Version 2.0.0

### PR DESCRIPTION
**Pull request by MRDGH2821**
This version now comes with slash command `/unbann-all` for unbanning users. (Thus removing the legacy command `!unbanall`)

Updated the README.md to reflect the following changes.

Added README_old.md for v1.x bots (v1.0.0 & v1.1.0)

### CODE REVIEW

**Comment by MRDGH2821** [comment]
Along with these changes, it would be nice to edit the description in the releases page.

For the initial release, add "Bot version 1.0.0"

For the 2nd release, add "Bot version 1.1.0"

**Comment by MRDGH2821** [comment]
This time the PR will have conflicts, so do not worry, accept the changes I have made

**Comment by Ryheff24** [comment]
I like the idea of using Slash commands with this, but the main reason I would like to keep it the way it is because operations are simple and easy. Theres a few things that could make the current code better like giving the user an invite of the bot without input of a client id. I feel like theres just to many steps when your setting this up for someone who may not know whats happening when they come accross errors. In the end I made this for someone who doesn't know how to code or set something up if they search like "discord mass unbanner" on google.

**Comment by Ryheff24** [comment]
Also, the wording of the readme I made is somewhat bad so I think that could be redone and have everyone clone the repo instead of using releases.

**Comment by MRDGH2821** [comment]
To be real, Discord themselves will remove the support for prefix-based commands (which rely on the Privileged Message Intent) by April 2022 (or was it 2024🤔)

Anyways, I have an idea, I'll separate the slash command version & prefix version into different README files and the code itself as well.

So, the users will have both choices to go for. In this way your thought process is satisfied and my so-called urge to encourage people to use Slash commands will also get fulfilled.

-----------

Here is what i'm thinking:

Renaming index.js to botv2.js
Adding botv1.js

in the package.json scripts, I'll add 2 scripts - `npm run bot1` & `npm run bot2`

**Comment by Ryheff24** [comment]
I didn't have time to actually run the code earlier when I commented, but I actually think it's good and not hard.

**Pull request merged**
